name: Deploy to Dokploy

on:
  push:
    branches: [main]

jobs:
  identify-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.set-apps.outputs.apps }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessary for Turbo to compare commits

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - id: set-apps
        name: Identify Changed Apps
        # This filters apps that changed relative to the previous commit
        run: |
          # APPS=$(bun x turbo build --filter='[HEAD^1]' --dry-run=json | jq -c '.packages | map(select(test("^//$|^@") | not))')
          APPS=$(bun x turbo build --filter=diw --dry-run=json | jq -c '.packages | map(select(test("^//$|^@") | not))')
          echo "Identified apps to deploy: $APPS"
          echo "apps=$APPS" >> $GITHUB_OUTPUT

  build-and-push:
    needs: identify-and-deploy
    if: ${{ needs.identify-and-deploy.outputs.apps != '[]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        app_name: ${{ fromJson(needs.identify-and-deploy.outputs.apps) }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: San-Diego-Fine-Woodworkers-Association
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase Owner Name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Get Application Version
        id: get_version
        run: |
          VERSION=$(jq -r '.version' apps/${{ matrix.app_name }}/package.json)
          echo "VERSION=$VERSION" >>${GITHUB_ENV}

      - name: Create Docker Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.OWNER_LC }}/${{ matrix.app_name }}
          tags: |
            type=raw,value=latest
            type=sha,format=short
            type=raw,value=${{ env.VERSION }}
          labels: |
            org.opencontainers.image.title=${{ matrix.app_name }}
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.app.prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            APP_NAME=${{ matrix.app_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Get Application ID Secret Name
        run: |
          CLEAN_NAME=$(echo "${{ matrix.app_name }}" | tr '-' '_' | tr '[:lower:]' '[:upper:]')
          APPLICATION_ID="DOKPLOY_APPLICATION_ID_$CLEAN_NAME"
          echo "APPLICATION_ID=$APPLICATION_ID" >>${GITHUB_ENV}

      - name: Deploy to Dokplo
        uses: benbristow/dokploy-deploy-action@0.2.2
        with:
          api_token: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
          application_id: ${{ secrets[env.APPLICATION_ID] }}
          dokploy_url: ${{ secrets.DOKPLOY_URL }}
          service_type: application